# Generated by Django 3.2 on 2021-04-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_calls', '0002_auto_20210412_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
    ]
